### ISSUE TITLE
Hooks order

### ISSUE THREAD

**Issue by rvision** [DoneDeal0/Talkr#16]
I am using talkr in the first bigger project and I find this very limitating: https://github.com/DoneDeal0/Talkr/issues/9

If you have rendering conditions, validations, notifications - the order of hooks forces you to get translated text into constants, which makes component code a mess very easily. This makes it almost useless. It also doesn't work in redux-saga, but fortunately I am not using it in this project.

I've tried to wrap it into some reusable function, but that is not possible either. 

Why this T can't be a function depending on hook reused everywhere? Something like const T = useT();

**Comment by DoneDeal0** [comment]
Hi @rvision , 

Yes, I didn't work on conditional rendering when writing the Talkr. I've done a first fix in #17 . It works thanks to a single `useT()` hook that export a function `T`. 

However, I'm afraid it will break the autocompletion, so I must do more tests. By the way, when you think something can be improved, feel free to send a pr ;).

**Comment by rvision** [comment]
@DoneDeal0 

Yes, IMHO https://github.com/DoneDeal0/Talkr/pull/17 looks much better, thanks.

I am no expert in TS and github collaboration flow, so I can't help you much except for written suggestions, sorry. 

Is there any chance to get rid of hooks dependency so this can be used in redux-saga for example? I've seen some discussion about this but didn't figure out what's planned.

I like the library because it's small and does what is it intented to do. I've chosen it because all other packages are way too big or have bunch of dependencies.

**Comment by DoneDeal0** [comment]
Alright, the code is ready. I can't login to npm for the moment, but I'll release the code as soon as possible. The master branch and the documentation are already updated, a release not has been published.

**Comment by rvision** [comment]
>Regarding the hooks, sorry, Talkr can't work without them. I'd just switch to Zustand or Jotai instead of Redux-Saga.

Zustand/Jotai are state managers, redux-saga is something else.
