### ISSUE TITLE
Translation helper for talkr

### ISSUE THREAD

**Issue by rvision** [DoneDeal0/Talkr#22]
I've created a small helper utility to ease the process of adding translations for talkr which I think it is useful:

![image](https://user-images.githubusercontent.com/1709545/159931077-2f12abf0-0d54-4812-aa77-8688a39c2aa0.png)

I am using talkr's T function through custom wrapper hook, useTranslation. In this hook I can choose to render original content of the talkr's hook - T(key) or I can render the clickable react component that prompts user to enter the translation. This translation object is set in the singleton which is copied on each translation to the clipboard, as formatted JSON so you can paste it in the file. Also it detects missing translations and puts them in the object so you can see immediately '*** missing ***' on the screen. It doesn't work for plurals or objects, only for strings.

Also it fires notifications in console if translation is missing (or same as in default locale):

![image](https://user-images.githubusercontent.com/1709545/159948629-731a0fe7-736e-4008-8705-360940265a88.png)

here is the gist:
https://gist.github.com/rvision/374faee770723d41f5cc376f03c953d5

**Comment by DoneDeal0** [comment]
Hi @rvision, thanks for sharing your work! However, issues are meant to report bugs. This topic would be more suitable in the discussion tab, or maybe in an article, where you could share your work process with other devs. I'm thus closing this issue.

**Comment by rvision** [comment]
@DoneDeal0 sorry, I haven't seen that tab until now :)

Can you move the post there or I should make a copy?

**Comment by rvision** [comment]
@DoneDeal0 nevermind, I've copied it there.
