### ISSUE TITLE
In SSR navigator is not defined

### ISSUE THREAD

**Issue by gshilin** [DoneDeal0/Talkr#3]

**Comment by gshilin** [comment]
`navigator` is not defined when is SSR mode. You use it to detect browser's language, but in this case it's impossible, so 'en' may be good enough instead of crash.

**Comment by DoneDeal0** [comment]
Hi Gshilin, thanks for using Talkr! Automatic language detection is an option. You can simply use write

```javascript
  <Talkr languages={{ en, fr }} defaultLanguage="en">
    <App />
  </Talkr>
```
to let the lib use "en" by default. However, I'll definitely add a fix to avoid any crash with automatic browser detection in case the it is not supported.

**Comment by gshilin** [comment]
This happens in https://github.com/DoneDeal0/Talkr/blob/ed261f3bfffc28bbfc6478f0375bc696c02f0702/src/index.tsx#L23 and that's not inside any condition.
The solution I found is to simulate `navigator`:
```js
if (typeof navigator === 'undefined') {
  navigator = {
    language: 'en-US',
  };
}
```
But it's quite ugly :(

**Comment by DoneDeal0** [comment]
I've just implemented the fix. It should be available on npm very soon. Please note that t() has been updated to T() in v 2.0.0 because of a Typescript issue.

**Comment by DoneDeal0** [comment]
The correct version is 2.0.2 or superior. The 2.0.1 has an export bug. Npm hasn't updated the package yet, please wait for this version to be available before updating your own package.

**Comment by gshilin-sdb** [comment]
Looked at it. Unfortunately it'll return 
`Uncaught ReferenceError: navigator is not defined`.
You have to use 
```js
typeof navigator !== 'undefined'
```

**Comment by DoneDeal0** [comment]
Why? The script checks if `navigator` exists, so it should not crash if the latter is undefined. `detectBrowserLanguage && navigator ? browserLanguage : defaultLanguage`.

**Comment by gshilin-sdb** [comment]
![image](https://user-images.githubusercontent.com/57442654/98975413-bfad8a00-251e-11eb-83bc-121e1128d1eb.png)

**Comment by gshilin-sdb** [comment]
The script checks if `navigator` has truthful value, but if it doesn't exist if will crash

**Comment by lodmfjord** [comment]
I did a pull request which fixes this issue. 

https://github.com/DoneDeal0/Talkr/pull/6

**Comment by DoneDeal0** [comment]
@gshilin Sorry for the huge delay in my answer, I had a lot of work and completely forgot to tweak this undefined navigator issue in ssr. Thanks @lodmfjord  for taking care of that! I'll push the patch on npm by monday (hopefully this evening)!
