### ISSUE TITLE
Cannot be used with React Testing Library

### ISSUE THREAD

**Issue by LovelessCodes** [DoneDeal0/Talkr#40]
Trying to use Talkr with React Testing Library but getting multiple of these:
```
TypeError: Cannot read properties of undefined (reading 'translation_key')
 ❯ node_modules/talkr/dist/index.js:1:1234
```
and then it obviously fails the tests.

Used DOM: [happy-dom](https://github.com/capricorn86/happy-dom)

**Comment by DoneDeal0** [comment]
Hi @LovelessCodes, I don't know this DOM, could you please provide a reproducible example?

**Comment by LovelessCodes** [comment]
Thanks for getting back that fast.

I set-up a [CodeSandbox](https://codesandbox.io/p/devbox/vxmrf6) with said environment.    
I tried out JSDOM & happy-dom, both getting the same error on CodeSandbox.    
Although it is a different error, it should stem from the same problem.
```
RangeError: Incorrect locale information provided
 ❯ node_modules/.pnpm/talkr@3.4.1/node_modules/talkr/dist/index.js:1:1002
```

To run the test on CodeSandbox, run the command
```
pnpm vitest
```

**Comment by LovelessCodes** [comment]
Okay, I realized I wasn't using the Talkr provider.    
Using a custom render function works as expected.    
Sorry for any inconvenience I may have caused.    
For anyone that may or may not stumble upon this issue - create a `test-utils.ts` file and use something like this:
```ts
import { type RenderOptions, render } from "@testing-library/react";
import type { ReactElement } from "react";
import { Talkr } from "talkr";
import { en } from "../locale";

const AllTheProviders = ({ children }: { children: React.ReactNode }) => (
    <Talkr languages={{ en }} defaultLanguage="en">{children}</Talkr>
);

const customRender = (
    ui: ReactElement,
    options?: Omit<RenderOptions, "wrapper">,
) => render(ui, { wrapper: AllTheProviders, ...options });

export * from "@testing-library/react";
export { customRender as render };
```

**Comment by DoneDeal0** [comment]
No problem, I'm glad you were able to fix your problem! Feel free to check the source code, there are tests that use a context as well.
