### ISSUE TITLE
setLocale doesn't trigger change

### ISSUE THREAD

**Issue by rvision** [DoneDeal0/Talkr#5]
How to detect change of selected language and change the attribute of html element with react-helmet? 
Given this structure:
`import { Talkr, useLocale } from 'talkr';
const App = () => {
	const { locale } = useLocale();
	console.log(locale);

	return (
		<>
			<Helmet>
				<body className="theme1" />
                                <html lang={locale} />
				<title>Hello</title>
			</Helmet>
			<Talkr languages={{ en, fr, es }} defaultLanguage="en" detectBrowserLanguage>
                            <Page with language switcher that does setLocale />
                        </Talkr>
            </>
	);
};

export default App;`

locale change is never catch and App is never re-rendered. If I move <Helmet /> below Talkr, same result.

**Comment by DoneDeal0** [comment]
Hi @rvision sorry for the huge delay in my answer, I havn't checked Talkr's repo since two weeks. You can use Helmet with Talkr. Here is a sandbox exemple that use useLocale(): https://codesandbox.io/s/lucid-kepler-nzrnn?file=/src/App.tsx

Please let me know if it resolves your issue.

**Comment by lodmfjord** [comment]
I think it is possible that @rvision is calling useLocale outside the Talkr provider.

useLocale returns default values when called outside the provider, which can make it seem that setLocale is broken.

I created a pull request #7 that throws an error when useLocale is called outside the provider.

**Comment by rvision** [comment]
No, I am not calling useLocale outside the Talkr provider.

It works only if I move Talkr to the index.jsx. When in <App /> it doesn't.

`ReactDOM.render(
	<Provider store={store}>
		<Talkr languages={{ en, fr, es }} defaultLanguage="fr">
			<App />
		</Talkr>
	</Provider>,
	document.getElementById('app'),
);`

**Comment by lodmfjord** [comment]
sorry @rvision for the misunderstanding but the way you do it in in index.jsx is what I call inside the provider:
(App is a children of Talkr, useLocale is called inside App)

but in your earlier example you used useLocale before returning <Talkr 
(useLocale is called in same component that returns the provider, useLocale is not called inside the provider)

**Comment by rvision** [comment]
You're right for my first example. I expected to useLocale be refreshed therefore re-rendering whole app.

But - if this `<Talkr />` provider is in the `<App />` component, it doesn't work properly. useLocale is inside provider, but somehow it doesn't work. To me this is strange behaviour.

**Comment by lodmfjord** [comment]
OK here is an example of what I mean. One incorrect usage and one correct usage. I apologize for spelling errors.
```javascript
export const Test = () => {
 const locale = useLocale(); // Correct: returns correct provider since called inside the provider, see const App for further information

return (
<div>{locale}</div>
)
}

export const App = () => {
const locale = useLocale(); // Returns incorrect context since called outside the provider
return (
<Talkr languages={{ en, fr, es }} defaultLanguage="en" detectBrowserLanguage>
<Test />
</Talkr>
)
}

```
Only those components who are children of <Talkr have access to the context. So calling useLocale from the same component that calls <Talkr does not work.

**Comment by rvision** [comment]
That makes sense, thanks a lot.

**Comment by DoneDeal0** [comment]
Thanks for your detailed answer @lodmfjord ! I'm glad everything works for you now @rvision .
